In [ ]:
 Exercise 1: (Score : 1) Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. 
Exercise 2: (Score : 1) Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. 
Exercise 3: (Score : 1) Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4. 
Exercise 4: (Score : 1) Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 
Exercise 5: (Score : 1) Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe. 
Exercise 6: (Score : 1) Select the rows of the dataframe where the age is greater than or equal to 30. 
Exercise 7: (Score : 1) Convert this dataframe to a csv file and read that csv file, finally display the contents. 
Exercise 8: (Score : 1) Create a line plot using matplotlib pyplot that displays the population of four different cities over time. Each city should have its own line, and the x-axis should represent years (e.g. 2010, 2011, 2012, etc.) while the y-axis should represent the population. The data for the four cities is provided below: City A: [500000, 550000, 600000, 650000, 700000, 750000, 800000] City B: [800000, 850000, 900000, 950000, 1000000, 1050000, 1100000] City C: [1000000, 1050000, 1100000, 1150000, 1200000, 1250000, 1300000] City D: [1200000, 1250000, 1300000, 1350000, 1400000, 1450000, 1500000] 
Exercise 9: (Score : 1) Create a scatter plot using seaborn that shows the relationship between the number of hours studied and the test scores obtained by a group of students. Use the following data: Hours Studied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] Test Scores: [93, 57, 61, 54, 51, 53, 87, 81, 83, 85] 
Exercise 10: (Score : 1) Create a bar chart using matplotlib pyplot that shows the total sales for each month of the year. Use the following data: Month: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] Sales: [11860, 10480, 4997, 5523, 13965, 6011, 13158, 9533, 5158, 9058, 11346, 6675]

In [1]:
#Excercise1
import numpy as np
a1=np.arange(1,11)
print(a1)
r1=a1.reshape(2,5)
print(r1)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
#Excercise2
import numpy as np
a2=np.arange(1,20)
print(a2)
print(a2[5:15])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 6  7  8  9 10 11 12 13 14 15]


In [33]:
#excercise3Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4. 
#Create a Pandas series with the following data: 
# Then, add a new item to the series with the key 'pears' and the value 4. 
import pandas as pd
p1=pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
print(p1)
print('..................................................................')
p1['pears']=4
print(p1)

apples     3
bananas    2
oranges    1
dtype: int64
..................................................................
apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [55]:
#Exercise 4: (Score : 1) 
#Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 
df=pd.DataFrame({'name':['Ravi','Hari','Abhi','Kili','Kakka','Maram','RAman','Sachi','Lakshman','Rahul'],'Age':[12,32,34,32,23,24,25,43,31,28],'Gender':['M','M','F','M','F','M','F','M','F','M']})
df

name  Age Gender
0      Ravi   12      M
1      Hari   32      M
2      Abhi   34      F
3      Kili   32      M
4     Kakka   23      F
5     Maram   24      M
6     RAman   25      F
7     Sachi   43      M
8  Lakshman   31      F
9     Rahul   28      M

In [57]:
#Exercise 5: (Score : 1) Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe
df['ocupation']=['programmer','Manager','Analyst','Programer','Analyst','Manager','Programer','Manager','Programer','Manager']
df

name  Age Gender   ocupation
0      Ravi   12      M  programmer
1      Hari   32      M     Manager
2      Abhi   34      F     Analyst
3      Kili   32      M   Programer
4     Kakka   23      F     Analyst
5     Maram   24      M     Manager
6     RAman   25      F   Programer
7     Sachi   43      M     Manager
8  Lakshman   31      F   Programer
9     Rahul   28      M     Manager

In [81]:
#Exercise 6: (Score : 1) Select the rows of the dataframe where the age is greater than or equal to 30.
x=df[df['Age']>=30]
print(x)
print('.........................')
#print(df.isnull().sum())
print('.........................')
#df.isnull()


       name  Age Gender  ocupation
1      Hari   32      M    Manager
2      Abhi   34      F    Analyst
3      Kili   32      M  Programer
7     Sachi   43      M    Manager
8  Lakshman   31      F  Programer
.........................
.........................


In [83]:
#Exercise 7: (Score : 1) Convert this dataframe to a csv file and read that csv file, finally display the contents.
df.to_csv('sample_data.csv', index=False)
print('.........................')
df_from_csv = pd.read_csv('sample_data.csv') # Read the CSV file back into a new DataFrame
print('.........................')
print(df_from_csv)

.........................
.........................
       name  Age Gender   ocupation
0      Ravi   12      M  programmer
1      Hari   32      M     Manager
2      Abhi   34      F     Analyst
3      Kili   32      M   Programer
4     Kakka   23      F     Analyst
5     Maram   24      M     Manager
6     RAman   25      F   Programer
7     Sachi   43      M     Manager
8  Lakshman   31      F   Programer
9     Rahul   28      M     Manager


In [95]:
#Exercise 8: (Score : 1) Create a line plot using matplotlib pyplot that displays the population of four different cities over time. 
#Each city should have its own line, and the x-axis should represent years (e.g. 2010, 2011, 2012, etc.) 
#while the y-axis should represent the population. The data for the four cities is provided below: 
#City A: [500000, 550000, 600000, 650000, 700000, 750000, 800000] 
#City B: [800000, 850000, 900000, 950000, 1000000, 1050000, 1100000] 
#City C: [1000000, 1050000, 1100000, 1150000, 1200000, 1250000, 1300000] 
#City D: [1200000, 1250000, 1300000, 1350000, 1400000, 1450000, 1500000]
print('.......................................')

.......................................


In [104]:
#Exercise 9: (Score : 1) Create a scatter plot using seaborn that shows the relationship between 
#the number of hours studied and the test scores obtained by a group of students.
#Use the following data: 
#Hours Studied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
#Test Scores: [93, 57, 61, 54, 51, 53, 87, 81, 83, 85] 

In [ ]:
#Exercise 10: (Score : 1) Create a bar chart using matplotlib pyplot that shows the total sales for each month of the year. 
#Use the following data: 
#Month: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] 
#Sales: [11860, 10480, 4997, 5523, 13965, 6011, 13158, 9533, 5158, 9058, 11346, 6675]